#!/bin/sh

# shellcheck source=src/common/utilities/common-utilities
. "$SNAP/utilities/common-utilities"

DEFAULT_HTTP_PORT="80"
DEFAULT_HTTPS_PORT="443"
DEFAULT_HTTP_COMPRESSION="false"
DEFAULT_HTTP_NOTIFY_PUSH_REVERSE_PROXY="false"

: "${APACHE_PIDFILE:="/tmp/pids/httpd.pid"}"
export APACHE_PIDFILE

mkdir -p "$(dirname "$APACHE_PIDFILE")"
chmod 750 "$(dirname "$APACHE_PIDFILE")"

restart_apache_if_running()
{
	if apache_is_running; then
		# Restart apache by stopping it and letting systemd start it again.
		pid="$(apache_pid)"
		printf "Restarting apache... "
		if output="$(httpd-wrapper -k stop 2>&1)"; then
			while kill -0 "$pid" 2>/dev/null; do
				sleep 1
			done
			printf "done\n"
		else
			printf "error\n"
			echo "$output"
			return 1
		fi
	fi
}

apache_is_running()
{
	[ -f "$APACHE_PIDFILE" ]
}

wait_for_apache()
{
	wait_for_command "Waiting for Apache" apache_is_running
}

apache_pid()
{
	if apache_is_running; then
		cat "$APACHE_PIDFILE"
	else
		echo "Unable to get Apache PID as it's not yet running" >&2
		echo ""
	fi
}

apache_http_port()
{
	port="$(snapctl get ports.http)"
	if [ -z "$port" ]; then
		port="$DEFAULT_HTTP_PORT"
		apache_set_http_port $port
		apache_set_previous_http_port $port
	fi

	echo "$port"
}

apache_set_http_port()
{
	snapctl set ports.http="$1"
}

apache_https_port()
{
	port="$(snapctl get ports.https)"
	if [ -z "$port" ]; then
		port="$DEFAULT_HTTPS_PORT"
		apache_set_https_port $port
		apache_set_previous_https_port $port
	fi

	echo "$port"
}

apache_set_https_port()
{
	snapctl set ports.https="$1"
}

apache_previous_http_port()
{
	snapctl get private.ports.http
}

apache_set_previous_http_port()
{
	snapctl set private.ports.http="$1"
}

apache_previous_https_port()
{
	snapctl get private.ports.https
}

apache_set_previous_https_port()
{
	snapctl set private.ports.https="$1"
}

apache_http_compression_enabled()
{
	[ "$(apache_get_http_compression)" = "true" ]
}

apache_enable_http_compression()
{
	_apache_set_http_compression "true"
}

apache_disable_http_compression()
{
	_apache_set_http_compression "false"
}

apache_http_compression_has_changed()
{
	[ "$(apache_get_http_compression)" != "$(_apache_get_previous_http_compression)" ]
}

apache_get_http_compression()
{
	compression="$(snapctl get http.compression)"

	if [ -z "$compression" ]; then
		compression="$DEFAULT_HTTP_COMPRESSION"
		_apache_set_http_compression "$compression"
	fi

	echo "$compression"
}

_apache_set_http_compression()
{
	snapctl set http.compression="$1"
	_apache_set_previous_http_compression "$1"
}

_apache_get_previous_http_compression()
{
	snapctl get private.http.compression
}

_apache_set_previous_http_compression()
{
	snapctl set private.http.compression="$1"
}

apache_notify_push_reverse_proxy_enabled()
{
	[ "$(apache_get_notify_push_reverse_proxy_enabled)" = "true" ]
}

apache_enable_notify_push_reverse_proxy_enabled()
{
	_apache_set_notify_push_reverse_proxy_enabled "true"
}

apache_disable_notify_push_reverse_proxy_enabled()
{
	_apache_set_notify_push_reverse_proxy_enabled "false"
}

apache_notify_push_reverse_proxy_enabled_has_changed()
{
	[ "$(apache_get_notify_push_reverse_proxy_enabled)" != "$(_apache_get_previous_notify_push_reverse_proxy_enabled)" ]
}

apache_get_notify_push_reverse_proxy_enabled()
{
	notify_push_reverse_proxy="$(snapctl get http.notify-push-reverse-proxy)"

	if [ -z "$notify_push_reverse_proxy" ]; then
		notify_push_reverse_proxy="$DEFAULT_HTTP_NOTIFY_PUSH_REVERSE_PROXY"
		_apache_set_notify_push_reverse_proxy_enabled "$notify_push_reverse_proxy"
	fi

	echo "$notify_push_reverse_proxy"
}

_apache_set_notify_push_reverse_proxy_enabled()
{
	snapctl set http.notify-push-reverse-proxy="$1"
	_apache_set_previous_notify_push_reverse_proxy_enabled "$1"
}

_apache_get_previous_notify_push_reverse_proxy_enabled()
{
	snapctl get private.http.notify-push-reverse-proxy
}

_apache_set_previous_notify_push_reverse_proxy_enabled()
{
	snapctl set private.http.notify-push-reverse-proxy="$1"
}
