#!/bin/sh

DEFAULT_MODE="production"

debug_mode_enabled()
{
	[ "$(_get_mode)" = "debug" ]
}

enable_debug_mode()
{
	_set_mode "debug"
}

production_mode_enabled()
{
	[ "$(_get_mode)" = "production" ]
}

enable_production_mode()
{
	_set_mode "production"
}

mode_has_changed()
{
	[ "$(_get_mode)" != "$(_get_previous_mode)" ]
}

_get_mode()
{
	mode="$(snapctl get mode)"
	if [ -z "$mode" ]; then
		mode="$DEFAULT_MODE"
		_set_mode "$mode"
	fi

	echo "$mode"
}

_set_mode()
{
	snapctl set mode="$1"
	_set_previous_mode "$1"
}

_get_previous_mode()
{
	snapctl get private.mode
}

_set_previous_mode()
{
	snapctl set private.mode="$1"
}