#!/bin/sh

CONFIGURE_LOCKFILE="/tmp/locks/configure-hook"

mkdir -p -m 750 "$(dirname $CONFIGURE_LOCKFILE)"

configure_hook_running()
{
	[ -f "$CONFIGURE_LOCKFILE" ]
}

set_configure_hook_running()
{
	touch "$CONFIGURE_LOCKFILE"
}

set_configure_hook_not_running()
{
	rm -f "$CONFIGURE_LOCKFILE"
}

wait_for_configure_hook()
{
	if configure_hook_running; then
		echo -n "Waiting for configure hook... "
		while configure_hook_running; do
			sleep 1
		done
		echo "done"
	fi
}
