#!/bin/sh

mkdir -p -m 750 $SNAP_DATA/apache/logs

# Make sure Nextcloud is installed and running
echo "Making sure nextcloud is setup..."
setup_nextcloud
if [ $? -ne 0 ]; then
	echo "Failed to setup nextcloud"
        exit 1
fi

echo "All set! Running httpd..."
httpd-wrapper $@
