#!/bin/sh

mkdir -p -m 750 $SNAP_DATA/apache/logs

# Setup SSL certificate
RO_APACHE_CONF_FOLDER=$SNAP/conf
RW_APACHE_CONF_FOLDER=$SNAP_DATA/apache/conf
if [ ! -d $RW_APACHE_CONF_FOLDER ]; then
	mkdir -p -m 750 $RW_APACHE_CONF_FOLDER
	echo "Copying SSL config files"
	cp $RO_APACHE_CONF_FOLDER/custom.conf $RW_APACHE_CONF_FOLDER
fi
mkdir -p -m 750 $SNAP_DATA/apache/conf

# Make sure Nextcloud is installed and running
echo "Making sure nextcloud is setup..."
setup_nextcloud
if [ $? -ne 0 ]; then
	echo "Failed to setup nextcloud"
        exit 1
fi

echo "All set! Running httpd..."

. $SNAP/utilities/https-utilities

# Rewrite live cert symlinks that aren't using the current symlink.
# FIXME: Remove this migration once epochs and upgrade hooks are available.
if certificates_are_active; then
	self_signed_basename="$(basename $SELF_SIGNED_DIRECTORY)"
	if [ "$(basename $(realpath $LIVE_CERTS_DIRECTORY))" = "$self_signed_basename" ]; then
		activate_self_signed_certificate
	else
		activate_certbot_certificate
	fi
fi

httpd-wrapper $@
