#!/bin/bash

set -e
set -x

# abort script in case nextant has been previously configured
if [ -e $SNAP_DATA/.nextant_configured ]; then
	exit 0
fi

PRODUCT=nextant
NEXTCLOUD_APPS_FOLDER=$SNAP_DATA/nextcloud/extra-apps

#include sed in path
export PATH=$PATH:$SNAP/$PRODUCT/bin

# Config default values
SOLR_TIMEOUT=30
SOLR_URL="http://127.0.0.1:8983/solr/"
SOLR_CORE="nextant"

CONFIGURED=2
INDEX_FILES_NEEDED=1
INDEX_LIVE=2

# wait for apps folder to be created before deploying our app files
while [ ! -e $NEXTCLOUD_APPS_FOLDER ]; do
    sleep 10
done

[ -e $NEXTCLOUD_APPS_FOLDER/$PRODUCT ]  || cp -rf $SNAP/$PRODUCT $NEXTCLOUD_APPS_FOLDER

# wait for nextcloud script finish its configuration process before continueing trying to deploy nextant
while [ ! -d $SNAP_DATA/nextcloud/config ]; do
	sleep 30
done

# enable nextant app. Retry until having nextcloud configured
while ! $SNAP/bin/occ app:enable $PRODUCT; do
    sleep 30
done

# configure with default parameters
$SNAP/bin/occ config:app:set $PRODUCT configured --value="$CONFIGURED"
$SNAP/bin/occ config:app:set $PRODUCT index_files_needed --value="$INDEX_FILES_NEEDED"
$SNAP/bin/occ config:app:set $PRODUCT index_live --value="$INDEX_LIVE"

$SNAP/bin/occ config:app:set $PRODUCT solr_timeout --value="$SOLR_TIMEOUT"
$SNAP/bin/occ config:app:set $PRODUCT sorl_url --value="$SOLR_URL"
$SNAP/bin/occ config:app:set $PRODUCT solr_core --value="$SOLR_CORE"

# kind of workaround to avoid using UI
$SNAP/bin/occ $PRODUCT:check --fix

# index
$SNAP/bin/occ $PRODUCT:index

## XXX (rmescandon): -i option to update over same file is not working in confined mode. Thus, this copy of file is made
# Ideally, should be:
# sed -i "/<?xml version=\"1.0\" encoding=\"UTF-8\" ?>/a <!DOCTYPE config [\n\t<!ENTITY nextant_component SYSTEM \"$NEXTANT_SOLR_CONFIG_FILE\">\n\t]>" $SOLR_CONFIG_FILE
# sed -i "/<\/config>/i &nextant_component;" $SOLR_CONFIG_FILE
# but instead:
NEXTANT_SOLR_CONFIG_FILE=$NEXTCLOUD_APPS_FOLDER/$PRODUCT/config/nextant_solrconfig.xml
SOLR_CONFIG_FILE=$SNAP_DATA/solr/$PRODUCT/conf/solrconfig.xml
TMP1_FILE=$SNAP_DATA/solr/$PRODUCT/conf/tmp1.xml
TMP2_FILE=$SNAP_DATA/solr/$PRODUCT/conf/tmp2.xml
sed "/<\/config>/i &nextant_component;" $SOLR_CONFIG_FILE > $TMP1_FILE
sed "/<?xml version=\"1.0\" encoding=\"UTF-8\" ?>/a <!DOCTYPE config [\n\t<!ENTITY nextant_component SYSTEM \"$NEXTANT_SOLR_CONFIG_FILE\">\n\t]>" $TMP1_FILE > $TMP2_FILE
mv $TMP2_FILE $SOLR_CONFIG_FILE
rm $TMP1_FILE

# this stop will force solr service to restart, as we wish.
$SNAP/bin/solr-server stop

# mark this as configured to avoid doing it again second and next times
touch $SNAP_DATA/.nextant_configured
