source 'https://rubygems.org'

# Test driver
gem 'capybara'

# Webdriver for chrome headless
gem 'selenium-webdriver'
gem 'base64'
gem 'logger'

# Use nice acceptance tests DSL
gem 'rspec'

# Run tests nicely
gem 'rake'
