source 'https://rubygems.org'

# Test driver
gem 'capybara'

# Webdriver for chrome headless
gem 'selenium-webdriver'

# Gem to get us the chrome driver
gem 'webdrivers'

# Use nice acceptance tests DSL
gem 'rspec'

# Run tests nicely
gem 'rake'
