#!/bin/sh

export MYSQL_PIDFILE="/tmp/pids/mysql.pid"
export MYSQL_SOCKET="/tmp/sockets/mysql.sock"

mkdir -p -m 750 "$(dirname $MYSQL_PIDFILE)"
mkdir -p -m 750 "$(dirname $MYSQL_SOCKET)"

mysql_is_running()
{
	[ -f "$MYSQL_PIDFILE" -a -S "$MYSQL_SOCKET" ]
}

wait_for_mysql()
{
	if ! mysql_is_running; then
		echo -n "Waiting for MySQL... "
		while ! mysql_is_running; do
			sleep 1
		done
		echo "done"
	fi
}

mysql_pid()
{
	if mysql_is_running; then
		cat "$MYSQL_PIDFILE"
	else
		echo "Unable to get MySQL PID as it's not yet running" >&2
		echo ""
	fi
}
