#!/bin/sh

mkdir -p -m 750 ${SNAP_DATA}/php

mysqld_pid_file_path=$SNAP_DATA/mysql/`hostname`.pid
# Wait for mysql to be up and running, since we need to make sure
# we run the upgrade process.
echo "Waiting for mysql..."
while [ ! -f "$mysqld_pid_file_path" ]; do
	sleep 1
done

# Wait until we have an nextcloud mysql password
echo "Obtaining nextcloud mysql credentials..."
nextcloud_password_path=$SNAP_DATA/mysql/nextcloud_password
timeout=10
while [ $timeout -gt 0 -a ! -e $nextcloud_password_path ]; do
	timeout=$((timeout-1))
	sleep 1
done
if [ ! -e $nextcloud_password_path ]; then
	echo -n "Timed out while attempting to obtain nextcloud mysql password. "
	echo -n "This isn't unusual when starting up for the first time after "
	echo "an install or an upgrade. Will try again."
	exit 1
fi

# Tends to be between 30-50MB
average_php_memory_requirement=50
total_memory=$(awk '/MemTotal/ {printf "%d", $2/1024}' /proc/meminfo)
export PHP_FPM_MAX_CHILDREN=$(($total_memory/$average_php_memory_requirement))

php-fpm -R -F --fpm-config ${SNAP}/config/php/php-fpm.conf -c ${SNAP}/config/php
