#!/bin/sh

# shellcheck source=src/common/utilities/common-utilities
. "$SNAP/utilities/common-utilities"

export REDIS_PIDFILE="/tmp/pids/redis.pid"
export REDIS_SOCKET="/tmp/sockets/redis.sock"

mkdir -p "$(dirname "$REDIS_PIDFILE")"
mkdir -p "$(dirname "$REDIS_SOCKET")"
mkdir -p "$SNAP_DATA/redis"
chmod 750 "$(dirname "$REDIS_PIDFILE")"
chmod 750 "$(dirname "$REDIS_SOCKET")"
chmod 750 "$SNAP_DATA/redis"

redis_is_running()
{
	[ -f "$REDIS_PIDFILE" ] && [ -S "$REDIS_SOCKET" ]
}

wait_for_redis()
{
	wait_for_command "Waiting for redis" redis_is_running
}

redis_pid()
{
	if redis_is_running; then
		cat "$REDIS_PIDFILE"
	else
		echo "Unable to get redis PID as it's not yet running" >&2
		echo ""
	fi
}
