name: Daily builds

on:
  schedule:
  - cron: "0 0 * * *"

jobs:
  generate:
    runs-on: ubuntu-latest
    environment: launchpad
    steps:
      - name: Check out code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          # Fetch all history so we can push
          fetch-depth: 0

      - name: Setup git
        run: |
          git config user.name "CI Bot"
          git config user.email "nextcloud-snappy-bot@git.launchpad.net"
          git remote add deploy git+ssh://nextcloud-snappy-bot@git.launchpad.net/nextcloud-snap

      - name: Setup SSH
        uses: webfactory/ssh-agent@e83874834305fe9a4a2997156cb26c5de65a8555 # v0.10.0
        with:
            ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Setup launchpad keys
        run: echo "${{ vars.LAUNCHPAD_SSH_PUBLIC_KEYS }}" > ~/.ssh/known_hosts

      - name: Spawn builds
        run: ./.github/spawn-dailies.sh
