name: Test daily builds

on:
  schedule:
  - cron: "0 5 * * *"

jobs:
  test-daily-master:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Install nextcloud
        run: sudo snap install --edge nextcloud

      - name: Setup ruby
        uses: ruby/setup-ruby@a30dfa457ad68707b8b910ac3a244714b61c0626 # v1.320.0
        with:
          working-directory: tests
          bundler-cache: true

      - name: Run tests
        working-directory: tests
        run: bundle exec ./run-tests.sh integration

  test-daily-v32:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Install nextcloud
        run: sudo snap install nextcloud --channel=32/edge

      - name: Setup ruby
        uses: ruby/setup-ruby@a30dfa457ad68707b8b910ac3a244714b61c0626 # v1.320.0
        with:
          working-directory: tests
          bundler-cache: true

      - name: Run tests
        working-directory: tests
        run: bundle exec ./run-tests.sh integration
  
  test-daily-v33:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Install nextcloud
        run: sudo snap install nextcloud --channel=33/edge

      - name: Setup ruby
        uses: ruby/setup-ruby@a30dfa457ad68707b8b910ac3a244714b61c0626 # v1.320.0
        with:
          working-directory: tests
          bundler-cache: true

      - name: Run tests
        working-directory: tests
        run: bundle exec ./run-tests.sh integration
